### ISSUE TITLE
visit http2 website will raise error

### ISSUE THREAD

**Issue by qiankunxienb** [CUCyber/ja3transport#6]
the target url is: https://http2.golang.org/

when I use ja3transport, the return is: 

> Get "https://http2.golang.org/": tls: server selected unsupported protocol version 304

**Comment by t94j0** [comment]
JA3transport does not support http/2 because, from what I can understand from the documentation, the [UTLS](https://pkg.go.dev/github.com/refraction-networking/utls@v0.0.0-20210713165636-0b2885c8c0d4) project does not support http/2.

I am not familiar enough with http/2 to know what would need to be done. If you understand the technology well and think you could implement such a thing, feel free to submit a pull request.

**Comment by qiankunxienb** [comment]
ok, thanks.
